# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _graphext
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


VertexOffset = _graphext.VertexOffset
NormalOffset = _graphext.NormalOffset
ColorOffset = _graphext.ColorOffset
TextureOffset = _graphext.TextureOffset
IndexOffset = _graphext.IndexOffset
DrawElementsVB = _graphext.DrawElementsVB
GetGLError = _graphext.GetGLError
GLErrorString = _graphext.GLErrorString
class DataBlock(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DataBlock, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DataBlock, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _graphext.new_DataBlock(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _graphext.delete_DataBlock
    __del__ = lambda self : None;
DataBlock_swigregister = _graphext.DataBlock_swigregister
DataBlock_swigregister(DataBlock)

class VertexBufferObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VertexBufferObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VertexBufferObject, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _graphext.new_VertexBufferObject(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _graphext.delete_VertexBufferObject
    __del__ = lambda self : None;
VertexBufferObject_swigregister = _graphext.VertexBufferObject_swigregister
VertexBufferObject_swigregister(VertexBufferObject)



